// GENERATED by scripts/gen-country-centroids.mjs — do not hand-edit.
// Centroids are the geoCentroid() of each country's LARGEST landmass in the same
// world-atlas 110m land data src/globe/land.ts already renders (a
// land-area centroid, not a capital or population centroid — consistent
// with how the rest of the app already draws these borders). Kept as plain
// JSON (countryCentroids.json) so both this typed module AND the Worker
// (worker/src/index.ts) and probe scripts (plain .mjs, no ts-node) can all
// read the exact same generated table without re-deriving it.
import raw from "./countryCentroids.json";

export const COUNTRY_CENTROIDS: Record<string, [lon: number, lat: number]> = raw as unknown as Record<
  string,
  [number, number]
>;
